os: linux
dist: xenial
language: dart
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
install:
  - git clone https://github.com/flutter/flutter.git $HOME/flutter
  - $HOME/flutter/bin/flutter doctor
  - $HOME/flutter/bin/flutter pub global activate --source git https://github.com/ThexXTURBOXx/intl_utils.git --overwrite
script:
  - echo -e "CONSUMER_KEY=SampleKey\nCONSUMER_SECRET=SampleSecret\nSENTRY_DSN=https://0@o0.ingest.sentry.io/0" > .env
  - $HOME/flutter/bin/flutter pub get
  - $HOME/flutter/bin/flutter pub global run intl_utils:generate
  - flutter pub run build_runner build
  - $HOME/flutter/bin/flutter analyze
cache:
  directories:
    - $HOME/.pub-cache