name: studipassau
description: StudiPassau Reimagined using Flutter
homepage: https://play.google.com/store/apps/details?id=studip_uni_passau.femtopedia.de.unipassaustudip
repository: https://github.com/ThexXTURBOXx/studipassau
issue_tracker: https://github.com/ThexXTURBOXx/studipassau/issues

publish_to: 'none'

version: 0.9.2+092

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  black_hole_flutter: ^0.3.2
  cached_network_image: ^3.1.0
  catcher: ^0.6.7
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  dart_date: ^1.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_cache_manager: ^3.1.2
  flutter_colorpicker: ^1.0.3
  flutter_dotenv: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.0.1+1
  flutter_secure_storage: ^5.0.2
  flutter_sticky_header: ^0.6.1
  flutter_web_auth: ^0.4.0
  http: ^0.13.4
  intl: ^0.17.0
  openmensa: ^2.0.0
  package_info_plus: ^1.0.4
  pref: ^2.5.0
  quick_actions: ^0.6.0+3
  sentry: ^6.0.1
  sentry_flutter: ^6.0.1
  share_plus: ^4.0.3
  sprintf: ^6.0.0
  studip: ^2.1.0
  supercharged: ^2.1.1
  timetable: ^1.0.0-alpha.7
  timezone: ^0.8.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_lints: ^2.0.1

dependency_overrides:
  catcher:
    git:
      url: https://github.com/ThexXTURBOXx/catcher.git
  flutter_web_auth:
    git:
      url: https://github.com/noga-dev/flutter_web_auth.git
  timetable:
    git:
      url: https://github.com/ThexXTURBOXx/timetable.git

flutter_icons:
  adaptive_icon_background: '#2898f1'
  adaptive_icon_foreground: 'assets/icons/studipassau_icon.png'
  android: true
  image_path: 'assets/icons/studipassau_icon.png'
  ios: true

flutter:
  assets:
    # Load the environment file with consumer key and secret
    - .env
    # env2 is only used for testing purposes
    - .env2
    # We also want the icons in some places
    - assets/icons/
  fonts:
    - family: StudiPassauIcons
      fonts:
        - asset: fonts/StudiPassauIcons.ttf
  uses-material-design: true

flutter_intl:
  enabled: true
  localizely:
    project_id: 32cea4c8-ff53-4e34-94d8-bcdc8643b236

flutter_native_splash:
  color: '#2898f1'
  image: assets/icons/studipassau_icon.png
