name: studipassau
description: StudiPassau Reimagined using Flutter
homepage: https://play.google.com/store/apps/details?id=studip_uni_passau.femtopedia.de.unipassaustudip
repository: https://github.com/ThexXTURBOXx/studipassau
issue_tracker: https://github.com/ThexXTURBOXx/studipassau/issues

publish_to: 'none'

version: 0.9.6+096

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '>=3.3.5'

dependencies:
  black_hole_flutter: ^0.3.2
  cached_network_image: ^3.1.0
  catcher: ^0.6.7
  collection: ^1.15.0
  dart_date: ^1.1.0
  envied: ^0.2.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_cache_manager: ^3.1.2
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.0.1+1
  flutter_secure_storage: ^6.0.0
  flutter_sticky_header: ^0.6.1
  flutter_web_auth_2: ^2.0.0
  http: ^0.13.4
  intl: ^0.17.0
  open_filex: ^4.1.1
  openmensa: ^2.1.0
  package_info_plus: ^3.0.0
  path_provider: ^2.0.11
  pref: ^2.5.0
  quick_actions: ^1.0.0
  sentry: ^6.0.1
  sentry_flutter: ^6.0.1
  share_plus: ^6.0.0
  shared_preferences: ^2.0.15
  sn_progress_dialog: ^1.0.8
  sprintf: ^7.0.0
  studip: ^2.1.0
  supercharged: ^2.1.1
  timetable: ^1.0.0-alpha.8
  timezone: ^0.9.0
  tuple: ^2.0.1
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.1.11
  envied_generator: ^0.2.3
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1

dependency_overrides:
  catcher:
    git:
      url: https://github.com/ThexXTURBOXx/catcher.git

flutter_icons:
  adaptive_icon_background: '#2898f1'
  adaptive_icon_foreground: 'assets/icons/studipassau_icon.png'
  android: true
  image_path: 'assets/icons/studipassau_icon.png'
  ios: true
  min_sdk_android: 18

flutter:
  assets:
    # We also want the icons in some places
    - assets/icons/
  fonts:
    - family: StudiPassauIcons
      fonts:
        - asset: fonts/StudiPassauIcons.ttf
  uses-material-design: true

flutter_intl:
  enabled: true
  localizely:
    project_id: 32cea4c8-ff53-4e34-94d8-bcdc8643b236

flutter_native_splash:
  color: '#2898f1'
  image: assets/icons/studipassau_icon.png
