name: studipassau
description: StudiPassau Reimagined using Flutter
homepage: https://play.google.com/store/apps/details?id=studip_uni_passau.femtopedia.de.unipassaustudip
repository: https://github.com/ThexXTURBOXx/studipassau
issue_tracker: https://github.com/ThexXTURBOXx/studipassau/issues

publish_to: 'none'

version: 0.9.0+090

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  black_hole_flutter: ^0.3.2
  cached_network_image: ^3.1.0
  catcher: ^0.6.7
  cupertino_icons: ^1.0.3
  dart_date: ^1.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_cache_manager: ^3.1.2
  flutter_dotenv: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_web_auth: ^0.4.0
  http: ^0.13.4
  intl: ^0.17.0
  openmensa: ^0.0.1
  package_info_plus: ^1.0.4
  quick_actions: ^0.6.0+3
  sentry: ^6.0.1
  sentry_flutter: ^6.0.1
  share_plus: ^3.0.4
  sprintf: ^6.0.0
  studip: ^2.1.0
  supercharged: ^2.1.1
  timetable: ^1.0.0-alpha.4
  timezone: ^0.8.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.0
  flutter_test:
    sdk: flutter

flutter_icons:
  adaptive_icon_background: '#2898f1'
  adaptive_icon_foreground: 'assets/icons/studipassau_icon.png'
  android: true
  image_path: 'assets/icons/studipassau_icon.png'
  ios: true

flutter:
  assets:
    # Load the environment file with consumer key and secret
    - .env
    # env2 is only used for testing purposes
    - .env2
  fonts:
    - family:  StudiPassauIcons
      fonts:
       - asset: fonts/StudiPassauIcons.ttf
  uses-material-design: true

flutter_intl:
  enabled: true
  localizely:
    project_id: 32cea4c8-ff53-4e34-94d8-bcdc8643b236

flutter_native_splash:
  android12: true
  color: '#2898f1'
  image: assets/icons/studipassau_icon.png
