name: studipassau
description: StudiPassau Reimagined using Flutter
homepage: https://play.google.com/store/apps/details?id=studip_uni_passau.femtopedia.de.unipassaustudip
repository: https://github.com/ThexXTURBOXx/studipassau
issue_tracker: https://github.com/ThexXTURBOXx/studipassau/issues

publish_to: 'none'

version: 1.1.1+111

environment:
  sdk: '>=3.0.0-417.3.beta <4.0.0'
  flutter: '>=3.10.0-1.4.pre'

dependencies:
  black_hole_flutter: ^1.0.1
  cached_network_image: ^3.1.0
  catcher: ^0.7.0
  collection: ^1.15.0
  dart_date: ^1.1.0
  device_info_plus: ^8.0.0
  easy_search_bar: ^2.5.0
  envied: ^0.3.0
  equatable: ^2.0.3
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_cache_manager: ^3.1.2
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_map: ^4.0.0-dev.2
  flutter_native_splash: ^2.0.1+1
  flutter_secure_storage: ^8.0.0
  flutter_sticky_header: ^0.6.1
  flutter_web_auth_2: ^2.0.0
  http: ^0.13.4
  intl: ^0.18.0
  latlong2: ^0.8.1
  maps_launcher: ^2.2.0
  open_filex: ^4.1.1
  openmensa: ^2.1.0
  package_info_plus: ^3.0.0
  path_provider: ^2.0.11
  pref: ^2.5.0
  quick_actions: ^1.0.0
  sentry: ^7.2.0
  sentry_flutter: ^7.2.0
  share_plus: ^6.0.0
  shared_preferences: ^2.0.15
  sn_progress_dialog: ^1.0.8
  sprintf: ^7.0.0
  string_similarity: ^2.0.0
  studip: ^2.1.0
  supercharged: ^2.1.1
  timetable: ^1.0.0-alpha.8
  timezone: ^0.9.0
  tuple: ^2.0.1
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.1.11
  envied_generator: ^0.3.0
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1

dependency_overrides:
  black_hole_flutter:
    git:
      url: https://github.com/ThexXTURBOXx/black_hole_flutter.git
  catcher:
    git:
      url: https://github.com/ThexXTURBOXx/catcher.git
  dart_date:
    git:
      url: https://github.com/ThexXTURBOXx/dart_date.git
      ref: patch-1
  easy_search_bar:
    git:
      url: https://github.com/4inka/flutter_easy_search_bar.git
  timetable:
    git:
      url: https://github.com/TatsuUkraine/timetable.git
      ref: intl-version-resolve

flutter_launcher_icons:
  adaptive_icon_background: '#2898f1'
  adaptive_icon_foreground: 'assets/icons/studipassau_icon.png'
  android: true
  image_path: 'assets/icons/studipassau_icon.png'
  ios: true
  min_sdk_android: 21

flutter:
  assets:
    # We also want the icons in some places
    - assets/icons/
    # Trusted root certificates (workaround for old Android)
    - assets/ca/
  fonts:
    - family: StudiPassauIcons
      fonts:
        - asset: fonts/StudiPassauIcons.ttf
  uses-material-design: true

flutter_intl:
  enabled: true
  localizely:
    project_id: 32cea4c8-ff53-4e34-94d8-bcdc8643b236

flutter_native_splash:
  color: '#2898f1'
  image: assets/icons/studipassau_icon.png
