name: studipassau
description: StudiPassau Reimagined using Flutter
homepage: https://play.google.com/store/apps/details?id=studip_uni_passau.femtopedia.de.unipassaustudip
repository: https://github.com/ThexXTURBOXx/studipassau
issue_tracker: https://github.com/ThexXTURBOXx/studipassau/issues

publish_to: 'none'

version: 0.9.0+090

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  cached_network_image: ^3.1.0
  catcher: ^0.6.7
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_dotenv: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  flutter_web_auth: ^0.3.0
  intl: ^0.17.0
  openmensa: ^0.0.1
  package_info_plus: ^1.0.4
  quick_actions: ^0.6.0+3
  sentry_flutter: ^5.1.0
  share_plus: ^2.1.4
  sprintf: ^6.0.0
  studip: ^2.1.0
  timetable: ^1.0.0-alpha.4
  timezone: ^0.7.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  # Use ephemeral patch and new Android dependency versions
  flutter_web_auth:
    git:
      url: https://github.com/ThexXTURBOXx/flutter_web_auth.git

flutter_icons:
  adaptive_icon_background: '#2898f1'
  adaptive_icon_foreground: 'assets/icons/studipassau_icon.png'
  android: true
  image_path: 'assets/icons/studipassau_icon.png'
  ios: true

flutter:
  assets:
    # Load the environment file with consumer key and secret
    - .env
    # env2 is only used for testing purposes
    - .env2
  fonts:
    - family:  StudiPassauIcons
      fonts:
       - asset: fonts/StudiPassauIcons.ttf
  uses-material-design: true

flutter_intl:
  enabled: true
  localizely:
    project_id: 32cea4c8-ff53-4e34-94d8-bcdc8643b236
