/// Flutter icons StudiPassauIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StudiPassauIcons
///      fonts:
///       - asset: fonts/StudiPassauIcons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class StudiPassauIcons {
  StudiPassauIcons._();

  static const _kFontFam = 'StudiPassauIcons';
  static const String? _kFontPkg = null;

  static const IconData github = IconData(
    0xf09b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData telegramPlane = IconData(
    0xf3fe,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
