name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create .env file
        run: echo -e "CLIENT_ID=SampleID" > .env

      - name: Activate own intl_utils
        run: dart pub global activate --source git https://github.com/ThexXTURBOXx/intl_utils.git --overwrite

      - name: Get dependencies
        run: flutter pub get

      - name: Generate language files
        run: dart pub global run intl_utils:generate

      - name: Generate env class
        run: dart run build_runner build

      - name: Lint
        run: dart format -o none --set-exit-if-changed .

      - name: Analyze
        run: dart analyze
