name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Flutter
        run: |
          echo "PUB_CACHE=${{ github.workspace }}/.pub-cache" >> $GITHUB_ENV
          ${{ github.workspace }}/.flutter/bin/flutter config --no-analytics
          echo "${{ github.workspace }}/.flutter/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/.flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      - name: Get dependencies
        run: flutter pub get

      - name: Generate additional files
        run: |
          dart run intl_utils:generate
          dart run build_runner build

      - name: Lint
        run: dart format -o none --set-exit-if-changed .

      - name: Analyze
        run: dart analyze
